service: objection-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  environment:
    OPENAI_API_KEY: ${param:OPENAI_API_KEY}

functions:
  ask:
    handler: handler.ask
    events:
      - httpApi:
          path: /ask
          method: post
# initial deploy
